apiVersion: skaffold/v2beta27
kind: Config
metadata:
  name: open-fi
build:
  local:
    push: false
    useBuildkit: true
  artifacts:
    - image: jasonwvh/auth
      context: auth
      docker:
        dockerfile: Dockerfile
        buildArgs:
          NPM_TOKEN: "{{.NPM_TOKEN}}"
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
    - image: jasonwvh/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "**/*.js"
            dest: .
deploy:
  kubectl:
    manifests:
      - infra/k8s/*
